function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 12-Jul-2023 00:19:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','f(x)','Marker','.','LineStyle','none');

% Create ylabel
ylabel({'f(x)'});

% Create xlabel
xlabel({'Real Number Line'});

% Create title
title({'Dirichlet Function'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1.25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.5 1.5]);
box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.783928571428569 0.873809523809524 0.0963387416208351 0.0426711309523861]);

