function createfigureAcc(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 04-Jul-2021 22:05:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1,'DisplayName','Time-Trace Acceleration','Color',[0.6350, 0.0780, 0.1840]);

% Create ylabel
ylabel({'Acceleration (m/s^2)'});

% Create xlabel
xlabel({'Signal Number'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.04 0.04]);
box(axes1,'on');
hold(axes1,'off');
% Create legend
ylim([-0.033 0.033])
yline(-0.02)
yline(0.02)
yline(0.01)
yline(-0.01)
yline(0)
yline(-0.03)
yline(0.03)